Page({
  data:{
    name:'test',
    age:123,
    student:[
      {id:'12',name:'测试',age:12},
      { id: '11',name: '测试1', age: 22}
    ],
    counter:0
  },
  //监听函数
 add(){
   this.setData({
     counter:this.data.counter+10
   })
 },
 remove(){
   this.setData({
     counter:this.data.counter-1
   })
 }
})